# Welcome to Serverless!
# Happy Coding!
service: import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false
  region: eu-west-1
  timeout: 20
  httpApi:
    cors: true
  
  environment:
    SQS_URL:
      Ref: SQSQueue

  iamRoleStatements:
    - Effect: Allow
      Action: "s3:ListBucket"
      Resource: 
        - "arn:aws:s3:::photo-wish-products-import"
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: 
        - "arn:aws:s3:::photo-wish-products-import/*"
    - Effect: Allow
      Action: "sqs:*"
      Resource:
        Fn::GetAtt: [ SQSQueue, Arn ]

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

package:
  individually: true

plugins:
  - serverless-webpack
  
functions:
  importProductsFile:
    handler: src/import-service/importProductsFile.handler
    events:
    - httpApi:
          method: GET
          path: /${self:provider.stage}/import
  importFileParser:
    handler: src/import-service/importFileParser.handler
    events:
      - s3:
          bucket: photo-wish-products-import
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: import-service-queue
  Outputs:
    SQSQueueUrl:
      Value:
        Ref: SQSQueue
      Export:
          Name: import-service-dev-SQSQueueUrl
    SQSQueueArn:
      Value:
        Fn::GetAtt: [ SQSQueue, Arn ]
      Export:
          Name: import-service-dev-SQSQueueArn