# Welcome to Serverless!
# Happy Coding!
service: products
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false
  region: eu-west-1
  timeout: 20
  environment:
    SQS_URL: 
      Fn::ImportValue: 'import-service-dev-SQSQueueUrl'
    SQS_ARN: 
      Fn::ImportValue: 'import-service-dev-SQSQueueArn'
    SNS_ARN:
      Ref: SNSTopic
    PG_HOST: 'photowish-products.cx9e2wg0ddmc.eu-west-1.rds.amazonaws.com'
    PG_PORT: '5432'
    PG_DATABASE: 'products'
    PG_USER: 'postgres'
    PG_PASSWORD : 'cRhRfHwUJ3k2b1ousdm4'
  
  iamRoleStatements:
    - Effect: Allow
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

package:
  individually: true

plugins:
  - serverless-webpack
  
functions:
  welcome:
    handler: src/product-service/welcome.handler
    events:
      - httpApi: 'GET /${self:provider.stage}'
  getProductsList:
    handler: src/product-service/getProductsList.handler
    events:
      - httpApi:
          method: GET
          path: /${self:provider.stage}/product/available
  getProductById:
    handler: src/product-service/getProductById.handler
    events:
      - httpApi:
          method: GET
          path: /${self:provider.stage}/product/{id}
  createProduct:
    handler: src/product-service/createProduct.handler
    events:
      - httpApi:
          method: POST
          path: /${self:provider.stage}/products
  catalogBatchProcess:
    handler: src/product-service/catalogBatchProcess.handler
    events:
      - sqs:
          batchSize: 5
          arn: ${self:provider.environment.SQS_ARN}

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: products-topic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: rusau.work@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic