# Welcome to Serverless!
# Happy Coding!

service: products
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false
  region: eu-west-1

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

package:
  individually: true

plugins:
  - serverless-webpack
  
functions:
  getProductsList:
    handler: handlers/getProductsList.handler
  getProductById:
    handler: handlers/getProductById.handler
#    events:
#      - http:
#          path: users/create
#          method: get
#      - websocket: $connect
#      - cloudwatchLog: '/aws/lambda/hello'
