# Welcome to Serverless!
# Happy Coding!

service: products
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false
  region: eu-west-1
  httpApi:
    cors: true

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

package:
  individually: true

plugins:
  - serverless-webpack
  
functions:
  getProductsList:
    handler: handlers/getProductsList.handler
    events:
      - httpApi: 'GET /product/available'
  getProductById:
    handler: handlers/getProductById.handler
    events:
      - httpApi:
          method: GET
          path: /product/{id}

